/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as MaisQueContabilidadeRouteImport } from './routes/mais-que-contabilidade'
import { Route as IrpfRouteImport } from './routes/irpf'
import { Route as CrescimentoRouteImport } from './routes/crescimento'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisQueContabilidadeRoute = MaisQueContabilidadeRouteImport.update({
  id: '/mais-que-contabilidade',
  path: '/mais-que-contabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IrpfRoute = IrpfRouteImport.update({
  id: '/irpf',
  path: '/irpf',
  getParentRoute: () => rootRouteImport,
} as any)
const CrescimentoRoute = CrescimentoRouteImport.update({
  id: '/crescimento',
  path: '/crescimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/crescimento': typeof CrescimentoRoute
  '/irpf': typeof IrpfRoute
  '/mais-que-contabilidade': typeof MaisQueContabilidadeRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/crescimento': typeof CrescimentoRoute
  '/irpf': typeof IrpfRoute
  '/mais-que-contabilidade': typeof MaisQueContabilidadeRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/crescimento': typeof CrescimentoRoute
  '/irpf': typeof IrpfRoute
  '/mais-que-contabilidade': typeof MaisQueContabilidadeRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/conteudos'
    | '/crescimento'
    | '/irpf'
    | '/mais-que-contabilidade'
    | '/solucoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/conteudos'
    | '/crescimento'
    | '/irpf'
    | '/mais-que-contabilidade'
    | '/solucoes'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/conteudos'
    | '/crescimento'
    | '/irpf'
    | '/mais-que-contabilidade'
    | '/solucoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ConteudosRoute: typeof ConteudosRoute
  CrescimentoRoute: typeof CrescimentoRoute
  IrpfRoute: typeof IrpfRoute
  MaisQueContabilidadeRoute: typeof MaisQueContabilidadeRoute
  SolucoesRoute: typeof SolucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais-que-contabilidade': {
      id: '/mais-que-contabilidade'
      path: '/mais-que-contabilidade'
      fullPath: '/mais-que-contabilidade'
      preLoaderRoute: typeof MaisQueContabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irpf': {
      id: '/irpf'
      path: '/irpf'
      fullPath: '/irpf'
      preLoaderRoute: typeof IrpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crescimento': {
      id: '/crescimento'
      path: '/crescimento'
      fullPath: '/crescimento'
      preLoaderRoute: typeof CrescimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ConteudosRoute: ConteudosRoute,
  CrescimentoRoute: CrescimentoRoute,
  IrpfRoute: IrpfRoute,
  MaisQueContabilidadeRoute: MaisQueContabilidadeRoute,
  SolucoesRoute: SolucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
